# Generated by Django 3.1.4 on 2021-06-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
